services:
  cliente:
    image: bryanpisco/kingstore-cliente:latest
    expose:
      - "3002"
    environment:
      PORT: "3002"
      HOSTNAME: "0.0.0.0"
    networks:
      - kingstore
    restart: unless-stopped

  admin:
    image: bryanpisco/kingstore-admin:latest
    expose:
      - "3001"
    environment:
      PORT: "3001"
      HOSTNAME: "0.0.0.0"
    networks:
      - kingstore
    restart: unless-stopped

  comerciante:
    image: bryanpisco/kingstore-comerciante:latest
    expose:
      - "3003"
    environment:
      PORT: "3003"
      HOSTNAME: "0.0.0.0"
    networks:
      - kingstore
    restart: unless-stopped

  backend:
    image: bryanpisco/kingstore-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JASYPT_ENCRYPTOR_PASSWORD: "${JASYPT_ENCRYPTOR_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    restart: unless-stopped

  gateway:
    image: bryanpisco/kingstore-gateway:latest
    ports:
      - "80:3000"
    environment:
      GATEWAY_PORT: "3000"
      CLIENTE_TARGET: "http://cliente:3002"
      ADMIN_TARGET: "http://admin:3001"
      COMERCIANTE_TARGET: "http://comerciante:3003"
    depends_on:
      - cliente
      - admin
      - comerciante
    networks:
      - kingstore
    restart: unless-stopped

networks:
  kingstore:
    driver: bridge
