export const MOCK_STORES = [
  {
    id: 'tenant-001',
    name: 'Canvas Lab',
    responsible: 'lucia@canvas.com',
    status: 'Activa',
    registrationDate: '01/03/2026',
    styles: ['Casual', 'Street'],
    prendas: ['Polo', 'Jean'],
    clientes: ['Dama', 'Unisex'],
    palette: 'core-street',
  },
  {
    id: 'tenant-002',
    name: 'Urban Style',
    responsible: 'marco@urban.com',
    status: 'Activa',
    registrationDate: '15/03/2026',
    styles: ['Street'],
    prendas: ['Casaca'],
    clientes: ['Caballero'],
    palette: 'utility-drop',
  },
  {
    id: 'tenant-003',
    name: 'Luxe Room',
    responsible: 'sofia@luxe.com',
    status: 'Suspendida',
    registrationDate: '20/03/2026',
    styles: ['Formal'],
    prendas: ['Vestido'],
    clientes: ['Dama'],
    palette: 'luxe-capsule',
  },
];

export const MOCK_USERS = [
  {
    name: 'Admin Plataforma',
    email: 'admin@plataforma.com',
    role: 'Administrador',
    store: 'N/A',
  },
  {
    name: 'Lucía Vega',
    email: 'lucia@canvas.com',
    role: 'Comerciante',
    store: 'Canvas Lab',
  },
  {
    name: 'Marco Torres',
    email: 'marco@urban.com',
    role: 'Comerciante',
    store: 'Urban Style',
  },
  {
    name: 'Sofía Ríos',
    email: 'sofia@luxe.com',
    role: 'Comerciante',
    store: 'Luxe Room',
  },
];

export const MOCK_AUDIT = [
  {
    time: '2026-05-07 09:14:02',
    user: 'admin@plataforma.com',
    role: 'Super Admin',
    tenant: 'Global',
    action: 'LOGIN',
    level: 'INFO',
  },
  {
    time: '2026-05-07 09:18:30',
    user: 'admin@plataforma.com',
    role: 'Super Admin',
    tenant: 'Canvas Lab',
    action: 'CREATE_STORE',
    level: 'SUCCESS',
  },
  {
    time: '2026-05-07 09:45:12',
    user: 'lucia@canvas.com',
    role: 'Comerciante',
    tenant: 'Canvas Lab',
    action: 'UPDATE_PRODUCT',
    level: 'INFO',
  },
  {
    time: '2026-05-07 10:02:55',
    user: 'system',
    role: 'System',
    tenant: 'Urban Style',
    action: 'SYNC_FAILED',
    level: 'WARNING',
  },
  {
    time: '2026-05-07 10:15:07',
    user: 'marco@urban.com',
    role: 'Comerciante',
    tenant: 'Urban Style',
    action: 'LOGIN_FAILED',
    level: 'ERROR',
  },
  {
    time: '2026-05-07 10:31:44',
    user: 'admin@plataforma.com',
    role: 'Super Admin',
    tenant: 'Luxe Room',
    action: 'SUSPEND_STORE',
    level: 'WARNING',
  },
];

export const MOCK_CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Polos',
    description: 'Camisetas y polos de todo tipo',
    status: 'Activa',
    use: 3,
    assignedStores: ['tenant-001', 'tenant-002', 'tenant-003'],
  },
  {
    id: 'cat-2',
    name: 'Casacas',
    description: 'Chaquetas, casacas y ropa de abrigo',
    status: 'Activa',
    use: 2,
    assignedStores: ['tenant-002'],
  },
  {
    id: 'cat-3',
    name: 'Accesorios',
    description: 'Gorras, bolsos y complementos',
    status: 'Inactiva',
    use: 0,
    assignedStores: [],
  },
];
